### ISSUE TITLE
get_measurement() on QuantumVariable not working correctly

### ISSUE THREAD

**Issue by wzpxq** [fraunhoferfokus/Qrisp#1]
Running the following code 

```
q = QuantumVariable(2) 
h(q)
q.get_measurement(shots = 2)
```

always gives the following output: 

`{'00': 0.0, '10': 0.0, '01': 0.0, '11': 0.0}`

If the number of shots is changed to 3, the output is: 

`{'00': 0.3333333333333333,
 '10': 0.3333333333333333,
 '01': 0.3333333333333333,
 '11': 0.3333333333333333}`

There are two issues with these outputs

- The output for each code version is always the same. Hence, actual measurements are not simulated, but rather probabilities as it seems
- The probabilities do not add up to 1 unless $s \equiv 0 \mod 2^n$ where $n$ is the number of qubits and $s$ is the number of shots 

More precisely, the calculated probabilities seem to be 
$$\frac{1}{s}\cdot \text{round}\left( \frac{s}{2 ^ n} \right)$$
But they should rather be $$\frac{1}{2^n}$$

**Comment by positr0nium** [comment]
With [0.2](https://www.qrisp.eu/general/changelog/0.2.html), the simulator now generates stochastic noise if queried with less than 10000 shots.
