### ISSUE TITLE
Unexpected behaviour of qRange

### ISSUE THREAD

**Issue by zickgraf** [fraunhoferfokus/Qrisp#10]
The code
```
from qrisp import QuantumFloat, qRange, h

n = QuantumFloat(3, signed = True, name = "n")
qf = QuantumFloat(5, name = "qf")
qf2 = QuantumFloat(5, name = "qf2")

n[:] = 4

for i in qRange(n):
    qf += 1
    qf2 += 1

    
print(qf)
print(qf2)
```
prints
```
{5: 1.0}
{0: 0.0312, 1: 0.0312, 2: 0.0312, 3: 0.0312, 4: 0.0312, 5: 0.0312, 6: 0.0312, 7: 0.0312, 8: 0.0312, 9: 0.0312, 10: 0.0312, 11: 0.0312, 12: 0.0312, 13: 0.0312, 14: 0.0312, 15: 0.0312, 16: 0.0312, 17: 0.0312, 18: 0.0312, 19: 0.0312, 20: 0.0312, 21: 0.0312, 22: 0.0312, 23: 0.0312, 24: 0.0312, 25: 0.0312, 26: 0.0312, 27: 0.0312, 28: 0.0312, 29: 0.0312, 30: 0.0312, 31: 0.0312}
```

Is this intended? I would expect `qf2` to have the same value as `qf`.

**Comment by positr0nium** [comment]
It is not intended, thank you for the report! It will be fixed in our next release.

**Comment by positr0nium** [comment]
With f99f460e929718f1519930a611b6bc2dd9a9f83c not only is this fixed but due to the new [ConjugationEnvironment](https://www.qrisp.eu/reference/Quantum%20Environments/ConjugationEnvironment.html) being used in the arithmetic module, the loop example can be compiled with about 30% less CNOT gates.
