### ISSUE TITLE
Listening on port 8080 by default causes issues

### ISSUE THREAD

**Issue by zickgraf** [fraunhoferfokus/Qrisp#4]
Qrisp seems to try to bind to and listen on port 8080 by default, e.g. when simply doing `from qrisp import QuantumVariable`. This has multiple issues:

1. 8080 is a rather common port. If this is port is already in use, e.g. by a webserver, importing Qrisp immediately leads to an error.
2. By default, one cannot open multiple instances of Qrisp at once.
3. By default, on a multi-user system only a single user can use Qrisp at a time.
4. On a multi-user system, any user can send arbitrary data to the Qrisp instance of another user. Does Qrisp authenticate connections? If not, this is a major security risk.

**Comment by positr0nium** [comment]
I agree with the first 3 points, regarding nr. 4: There is no exec call in the default backend's run function and the only data that will pass the server interface is serialized quantum circuits. The security risk (for users who exposed their ports) is therefore only a "DDOS" type, where a potential attacker could send a very large circuit. Nevertheless we will address this as well.

**Comment by zickgraf** [comment]
> There is no exec call in the default backend's run function and the only data that will pass the server interface is serialized quantum circuits.

But that quantum circuit will still be untrusted user input. For example, the name of an operation or the identifier of a Qubit can be an arbitrary string. So any code getting such a serialized quantum circuit has to take the possibility of malicious input into account. This can easily go wrong: For example, see the Log4j vulnerability for a recent example that simply using a logging framework with untrusted user input can lead to arbitrary code execution vulnerabilities. Thus, the security risk is not limited to  denial-of-service attacks.

**Comment by positr0nium** [comment]
With [0.2](https://www.qrisp.eu/general/tutorial.html), simulation requests are no longer transfered through the interface.
