### ISSUE TITLE
print(qv.qs) does not work

### ISSUE THREAD

**Issue by unico20** [fraunhoferfokus/Qrisp#9]
Hi all :) I have problems with printing circuits:
```
from qrisp import QuantumVariable
qv = QuantumVariable(1)
print(qv.qs)
```
yields
```
UserWarning: Style JSON file 'text.json' not found in any of these locations: /path/to/qiskit/visualization/styles/text.json, text.json. Will use default style.
  self._style, def_font_ratio = load_style(style)
QuantumCircuit:
---------------
Figure(220.973x451.5)
Live QuantumVariables:
----------------------
QuantumVariable qv_0
```
Does anyone know the file 'text.json' or have a clue how to get it?

I have python version `3.8.10` installed and the following `__qiskit_version__`: `{'qiskit-terra': '0.24.1', 'qiskit-aer': '0.12.0', 'qiskit-ignis': None, 'qiskit-ibmq-provider': '0.20.2', 'qiskit': '0.43.1', 'qiskit-nature': None, 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}`

Thanks a lot for any inspiration :-)

**Comment by positr0nium** [comment]
Hi, this seems like a Qiskit related problem. Did you try reinstalling Qiskit or installing a different version? My local version and the [GitHub repo](https://github.com/Qiskit/qiskit-terra/tree/main/qiskit/visualization) don't have the folder "styles"

**Comment by unico20** [comment]
Thanks a lot for your help.
Yes, I have reinstalled Qiskit and tried with other versions. 
I also tried with another Python version (3.10.12) and with virtual environments with
-  Qrisp and `qiskit[visualization]` installed 
-  Qrisp and `qiskit` installed 
-  Qrisp installed but _not_ Qiskit. In this case, I was asked to install `pylatexenc` in order to use `MatplotlibDrawer`

In all cases, I obtained a similar `UserWarning: Style JSON file 'text.json' not found in any of these locations: /path/to/qiskit/visualization/circuit/styles/text.json, text.json. `
What changed, however, is the `circuit` folder between `visualization` and `styles`. This new path also exists in the [GitHub repo](https://github.com/Qiskit/qiskit-terra/tree/main/qiskit/visualization/circuit/styles), but doesn't contain the searched file `text.json` either :(

**Comment by positr0nium** [comment]
Can you post the full error message including traceback?

**Comment by unico20** [comment]
Yes, I edited the message. Does that help?

**Comment by positr0nium** [comment]
Your folder structure is different from my local folder structure and also from the github page. The "visualization" folder doesn't contain a matplotlib file. The circuit sub folder contains one, but this file also doesn't contains no such user warning. To me, it seems like you **installed** the newest version of Qiskit to some environment, but try to **start** Qrisp/Qiskit (unintentionally) in a different environment. This would explain why your folder structure looks different. Maybe clear your PATH variable?

**Comment by positr0nium** [comment]
The warning you posted is in [this file now](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/visualization/circuit/qcstyle.py)

**Comment by unico20** [comment]
The whole path is
`home/unico/anaconda3/envs/Qrisp_env/lib/python3.10/site-packages/qiskit/visualization/matplotlib.py`
or similar: I used different environments (here: `Qrisp_env`) to try different versions of python/qiskit.

**Comment by positr0nium** [comment]
That file, matplotlib.py should not be in that folder. Can you try reinstalling from different sources (make a new environment for this):
If you used Conda for installation, try pip or try Conda if you previously used Conda.
If it still doesn't work, you can be super sure and install from source. For this follow these 

 
> Download the [Qiskit repo](https://github.com/Qiskit/qiskit-terra) either as a zip or using git 
> Create a new environment
> Open a console with that environment activated
> Navigate to the top folder (containing setup.py)
> Execute `pip install -e ./`

More info on installing from source [here](https://qiskit.org/documentation/contributing_to_qiskit.html#dev-env-setup)
